### ISSUE TITLE
Warning: INFO=23 likelihood calculation has failed due to variable 23

### ISSUE THREAD

**Issue by alexkrohn** [stephens999/scat#16]
Hi @stephens999,

I'm excited to try this program. I am using RADseq SNP data to approximate localities for three individuals from a reference dataset of 139 animals. Because you state that SCAT strongly prunes missing data and struggles with large datasets, I've filtered my data to remove a lot of missing data (although some is still present), and to only include 112 putatively unlinked SNPs. 

The input files are below: 
[85maxmissing-biallelic.vcf.str.txt](https://github.com/stephens999/scat/files/8959061/85maxmissing-biallelic.vcf.str.txt)
[boundary-file.txt](https://github.com/stephens999/scat/files/8959062/boundary-file.txt)
[location-file.txt](https://github.com/stephens999/scat/files/8959063/location-file.txt)

When I attempt to run a long chain, with assignment, I get an error regarding variable 23. Despite my best efforts, I cannot find more information on this error. Any idea what's going on here? Is it something with my location file?

Here is the code and the full error text. It's running on a Ubuntu 20.04. 
```
SCAT3 85maxmissing-biallelic.vcf.str.txt location-file.txt ../output-run1/ 112 100 1000 100 -A -Bboundary-file.txt -S 20
SCAT version 3.0.2
MAXNALLELE = 120
Reading Genotype Data
Inputting location information
Warning: INFO=23
This probably means likelihood calculation has failed due to variable 23
If the message continues to appear after burn-in the results cannot be trusted.
Segmentation fault (core dumped)
```

Thanks for your help! This program is exactly what my team is looking for!

**Comment by stephens999** [comment]
@mkkuhner any chance you could look into it?

**Comment by alexkrohn** [comment]
Thanks @stephens999. With a big more digging, it appears that `variable 23` refers to the population number of 23. It seems that SCAT didn't like individuals with high amounts of missing data. I went back through and removed individuals with missing data at > 30% of the sites. 

I also found that I had an error in the population numbers in the genotype file. I used PGDSpider to convert from VCF to Structure, but PGDSpider did not like assigning an individual to the population of `-1`. So, I fixed that too.

Alas, now the program does not run at all. I simply get a seg fault.

Here's the new data file, with the above corrections: [85maxmissing-missingindsremoved-biallelic.vcf.str.txt](https://github.com/stephens999/scat/files/8959477/85maxmissing-missingindsremoved-biallelic.vcf.str.txt)

And the code run to get the seg fault error:
```
SCAT3 85maxmissing-missingindsremoved-biallelic.vcf.str.txt location-file.txt ../output-run1/ 112 100 1000 100 -Bboundary-file.txt -S 20
SCAT version 3.0.2
MAXNALLELE = 120
Reading Genotype Data
Inputting location information
Segmentation fault (core dumped)
``` 

Could this be because any locus with any missing data is dropped? In which case, if all loci have at least one missing value, they're all dropped?

**Comment by mkkuhner** [comment]
Hi, this is Mary Kuhner, the current maintainer of SCAT.

It definitely does not drop loci with missing data or none of my datasets
would run.

This error indicates a failure to factor a matrix: the error message is
opaque because it's the result of a call to an external library and we
don't know (I don't, anyway) what's happening in there.

I have also seen this in my own data.  I have a couple of suggestions which
may or may not work:

(1)  Make sure that all of your reference populations are inside your
species boundaries.  Even a one degree mismatch here really messes things
up.  (Next version will check for this!)

(2)  Consider pooling small populations that are close to each other.

(3) Use a different analysis like FST to see how much population structure
you actually have.  SCAT works on an isolation by distance model and if
there is little or no structure it won't work.

I will give your data set a try and see if I can figure it out, but it is
not likely to be quick:  I have a similarly misbehaving data set and I've
been wrestling with it for a while.

Mary Kuhner ***@***.***

**Comment by alexkrohn** [comment]
Hi @mkkuhner! 

Good to know about missing data. That's a relief.

1) I checked this. There was one point that was off -- good call! I changed it, but still got the same error.  Here's the fixed [location data file](https://github.com/stephens999/scat/files/8960964/location-file.txt). Also, if I remove the -B flag, I get the same error, making me think it is not a problem with the bounding polygon.

2) I pooled as many pops as I could justify biologically. If I pooled more, it was degrade our ability to meaningfully put animals back in the wild (e.g. we'd be suggesting the animal came from one of two states, which changes the management decisions drastically. It is also known that the animals migrate very little.) Even when using the pooled datatset, I got the same seg fault error. If you're interested to play with the pooled data they're [here](https://github.com/stephens999/scat/files/8960999/85maxmissing-missingindsremoved-biallelic-localities-changed.vcf.str.txt).

3) FST values between the confiscated samples and the original (non-pooled) populations range from 0.005 with one population to 0.197 (median is 0.169). My intuition thinks that the population with the 0.005 FST value is likely close to the original location of the animals, but I'd still like to use SCAT to see if that hunch holds up. Looking at the PCA, I do think there should be enough structure to identify the confiscated individuals.

![pca](https://user-images.githubusercontent.com/12600348/175127387-4656af20-b4ab-44a5-bece-e36a70254b36.png)

Let me know when you get a chance to play with the data. I'm very curious what you find.

**Comment by stephens999** [comment]
it's just a guess, but now you no longer get the INFO error but a segfault error i would guess maybe it is some kind of error in the input file format....

**Comment by alexkrohn** [comment]
Hmm. It definitely is possible. I'm not sure what it could be though. This input file runs fine with STRUCTURE...

I'll keep looking too.

**Comment by mkkuhner** [comment]
Hi Alex,

My testing version of the program, which tests if all locations are within
the boundaries, does not like location CT even with your corrected
location-file.txt.

There is likely something else going on too.  Can you send me the run
command you used to run the program?  I am not replicating your seg-fault.

Mary

**Comment by alexkrohn** [comment]
Hi Mary. Good catch! I thought that CT sample would be inside, but I guess not. I moved it. Despite changing that locality to 41.594  -73.492,  I'm still getting the segfault when I run:
`SCAT3 85maxmissing-missingindsremoved-biallelic.vcf.str.txt location-file.txt output/ 112 100 1000 100 -A -Bboundary-file.txt -S 20`

I'm running SCAT3 on Ubuntu 20.04 if that helps.

**Comment by mkkuhner** [comment]
There are errors in this run line (which suggests I have work to do on the
documentation).  The -letter options have to come before the other
information, not after, and -A requires a start and stop.  Also, if you
only want to localize the unknown location individuals (-1 population) you
need to put those at the top of the input file and the -A should list just
that many.  So you'd move your three unknown individuals to the top, and
the command line would look like this:

SCAT3 -A 1 3 -Bboundary-file.txt -S 20 userdata.txt location-file.txt
output/ 112 100 1000 100

With those changes I can at least get it running. If you send me your
corrected locations file I will run it here and let you know what happens.

Mary

**Comment by alexkrohn** [comment]
Hi Mary! Hurray! Yes, this does work on my system. I apologize for the confusion over the order of flags. Any updates that you make are greatly appreciated. I'm glad someone is continuing to maintain this program.

Thanks again for your help!
