### ISSUE TITLE
Trouble compiling

### ISSUE THREAD

**Issue by gatoravi** [stephens999/scat#9]
I got some errors while trying to compile, I had to remove some lines from the Makefile (prefixed with '-' below) to compile succesfully using the command `make scat2`, this is my `git diff`:

```
diff --git a/src/Makefile b/src/Makefile
index dd01aba..660c0aa 100644
--- a/src/Makefile
+++ b/src/Makefile
@@ -17,7 +17,6 @@ CFLAGS = -g $(INCLUDE)
 LDFLAGS = -llapack
 #LDFLAGS = -llapack /usr/lib/gcc-lib/i386-redhat-linux/3.2.3/libg2c.a /usr/lib/libm.a

-SUFFIXES:
 .SUFFIXES: .cpp .o

 .cpp.o:
@@ -25,20 +24,15 @@ SUFFIXES:

 TESTOBJ = test.o test2.o

-OBJ = main.gaussianprocess.o utility.o
 HDR = utility.hpp utility.cpp
 OBJ2 = scat2.o utility.o mt19937ar.o

-SCAT : $(OBJ)
-   $(CXX) $(CFLAGS) -o $@ $^ $(LDFLAGS)
-
 SCAT2 : $(OBJ2)
        $(CXX) $(CFLAGS) -o $@ $^ $(LDFLAGS)

 test: $(TESTOBJ)
        $(CXX) $(CFLAGS) -o $@ $^ $(LDFLAGS)
```

Some additional targets could also be removed from the Makefile if not needed, like `main.gaussianprocess.o`. The file `main.gaussianprocess.cpp` seems to be missing from the repository!

**Comment by stephens999** [comment]
thanks!
Yes, the makefile is rather a mess. i think i edited it to match your suggestions. I'm sure it could be much further improved if you have time...

**Comment by gatoravi** [comment]
Thank you! I just made a pull-request with some small changes. Please feel free to resolve this issue.

**Comment by stephens999** [comment]
thanks for your contribution!
